name: Backend Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checking Out the code from Repo
        uses: actions/checkout@v3

      - name: Installing dependency manager pipenv
        run: pip install pipenv

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}
        
      - name: Installing dependencies
        run: |
          pipenv install --dev
          pipenv install flake8
          
      - name: Now Running Lint
        run: pipenv run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installing dependency
        run: pip install pipenv

      - name: Caching
        id: CachingData
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}

      - name: Installing dependencies
        run: |
          pipenv install --dev
          pipenv install flake8
  
      - name: Now Running Tests
        run: pipenv run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint,test]
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build ./starter/backend